version: '3.8'
services:
  BandHub.AuthService:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000 # 強制 Email 指向 MailHog
      - Email__Host=mailhog
      - Email__Port=1025
      - Email__EnableSsl=false
      - Email__From=noreply@tickets.local
      - Email__Username=
      - Email__Password=
    container_name: BandHub.AuthService
    ports:
      - "5000:5000"
    depends_on:
      - db
      - mailhog
    networks:
      - devnet
    volumes:
      - .:/workspace

  db:
    image: postgres:15
    container_name: my-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwer1@34
      POSTGRES_DB: TBHDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./document/TBHDB.sql:/docker-entrypoint-initdb.d/TBHDB.sql:ro
    networks:
      - devnet

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - devnet
    restart: unless-stopped

networks:
  devnet:


volumes:
  pgdata:
